# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02365b45d7e194b6499c4965b11aa175ac8c9092351a5a8bd1ab39685460aa47d40465877e0c43e4603a4d49a4cd257126c66951b3745d095dc0a6c13ceb04de

test:
  secret_key_base: 3a18384f12e7e05156a0c04aef1d799b8f312c8415161b0de6531cc6c7a52a10fa9d9b392ef4e8e256147db7a566128cdc2f398002ee92134bf6af6a88570035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
